### ISSUE TITLE
Alert output connection 

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFHT01#1]
Výstup Alert je připojen k napájení.

![image](https://user-images.githubusercontent.com/1194177/113597634-47b23e80-963c-11eb-848d-cab9cf3d272c.png)

Aktuální zapojení by pravděpodobně při sepnutí alert výstupu pravděpodobně vedlo k poškození senzoru.

**Comment by kaklik** [comment]
Alert pin by se mohlo hodit pro spínání indikační LED. Tím by bylo možné indikovat stavy snímače. Podle [dokumentace](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Sensirion_Humidity_Sensors_SHT3x_Application_Note_Alert_Mode_DIS.pdf) je však vhodné, aby LED byla spínána přes tranzistor, aby nedocházelo k ohřívání snímače nadměrným proudem.

**Comment by ChroustJan** [comment]
@kaklik a chceme tam další LED? Tranzistor to taky hodně zas zvedne.

**Comment by kaklik** [comment]
> @kaklik a chceme tam další LED? Tranzistor to taky hodně zas zvedne.

Co zvedne tranzistor?   Jestli myslíš velikost, tak si stále myslím, že není cílem udělat úplně nejmenší možné PCB. Potřebujeme jednotnou velikost PCB a kvalitní návrh. 
V případě tohoto čidla stále potřebuješ tepelnou izolaci mezi stabilizátorem a samotným snímačem.  Koukni se do [application note](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Application_Note/Sensirion_AppNotes_Humidity_Sensors_Design_Guide.pdf).

**Comment by ChroustJan** [comment]
@kaklik jakou logiku chceme mít u té LED? Zde by měla svítit když bude na alert H úroveň.
![image](https://user-images.githubusercontent.com/9783606/115024527-7e9c1600-9ec0-11eb-9ab4-014fd98563c4.png)

**Comment by kaklik** [comment]
> @kaklik jakou logiku chceme mít u té LED? Zde by měla svítit když bude na alert H úroveň.
>

Ano na Alert je log 1, když je aktivní.

**Comment by ChroustJan** [comment]
LED bude svítit při H na alert
