### ISSUE TITLE
ALERT LED failure

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFHT01#11]
Zjistil jsem, že na čidle vyndaném z meteoboxu, kde nesvítila ALERT LED. Bylo to tím, že byla vnitřně zkratovaná. 
Zřejmě se jí přihodilo něco nepříjemného, pochybuji, že by byla vadná z výroby. 

Řešení zřejmě souvisí jednak s tím, že by bylo vhodné layout upravit tak, aby zkratování nožičky LED (nejpravděpodobněji asi s GND) nemohlo LED zničit.  A taky je zřejmě potřeba nějak vyřešit zakrytování celého snímače #10

**Comment by ChroustJan** [comment]
Prohodil jsem LED s R: 
![image](https://github.com/ThunderFly-aerospace/TFHT01/assets/9783606/d60266c9-92c3-4f95-aac1-60571bd110c8)
