### ISSUE TITLE
Reset input connection

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFHT01#2]
datasheet vyžaduje připojení vstupu reset přes rezistor a nebo jeho zanechání v plovoucím stavu. 

![image](https://user-images.githubusercontent.com/1194177/113598085-e63e9f80-963c-11eb-9567-45b3709cc7e1.png)

**Comment by ChroustJan** [comment]
@kaklik tak pro nás je asi lepší ten plavoucí stav pokud to nevadí?

**Comment by kaklik** [comment]
> @kaklik tak pro nás je asi lepší ten plavoucí stav pokud to nevadí?

Tak v datasheetu píšou, že to nevadí..

**Comment by ChroustJan** [comment]
Zanechán v plavoucím stavu.
