### ISSUE TITLE
LED label

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFHT01#3]
@kaklik jaký by měl být text popisků LED?

**Comment by roman-dvorak** [comment]
navrhuji:
* PWR
* ALERT

**Comment by kaklik** [comment]
Jo Romanův návrh PWR je lepší než můj návrh ON, zde. https://github.com/ThunderFly-aerospace/TFI2CEXT01/issues/4#issuecomment-821993203. Navrhuju to sjednotit na PWR.

**Comment by ChroustJan** [comment]
Finální popisek:
PWR
ALERT
