### ISSUE TITLE
LED luminosity

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFHT01#4]
Zvážit zda chceme stejnou svítivost zelené a červené LED.

Červená je jasnější než zelená

**Comment by kaklik** [comment]
Je to potřeba třeba i pasivně namontovat na vírník a podívat se za reálných světelných podmínek, jak to vypadá.

**Comment by roman-dvorak** [comment]
Myslím, že takhle je ta svítivost v pořádku. Červená LEDka (ta jasnější) navíc značí chybový stav a za normálního provozu je zhasnutá. Takže je úplně v pořádku, že svítí více. 

Možná by si chtělo vytvořit nějaký interní standard ohledně barev LEDek, protože zde zelená ledka značí přítomnost napájení., což mi nepřijde moc běžné.

**Comment by kaklik** [comment]
> 
> Možná by si chtělo vytvořit nějaký interní standard ohledně barev LEDek, protože zde zelená ledka značí přítomnost napájení., což mi nepřijde moc běžné.

a jaká barva je typická pro napájení?  Mě přijde, že zelená je naopak pro tenhle účel hodně běžná.

**Comment by kaklik** [comment]
Pokud se tohle týká jen nejasnosti v barvách LED, tak si myslim, že zatím to lze takto uzavřít. Protože původní problém vedoucí k otevření issue pravděpodobně ve verzi B neexistuje díky změně layoutu #7
