### ISSUE TITLE
Sensor membrane

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFHT01#5]
Na další snímače by to chtělo osadit variantu senzorů s [krycím filtrem](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/2_Humidity_Sensors/Datasheets/Sensirion_Humidity_Sensors_SHT3x_Datasheet_Filter_Membrane.pdf), který by měl zabránit znečištění senzoru ve venkovním prostředí.

**Comment by roman-dvorak** [comment]
Na telefonu 4. 1. 2022 bylo dohodnuto, že se upraví PCB tak, aby podporoval montáž čepičky [CAP-SF2](https://www.sensirion.com/en/environmental-sensors/humidity-sensors/filter-cap-sf2/), která má být schopná zvýšit odolnost senzoru na IP67 (mělo by to být možné ponořit do vody). 

Pod čepičku se bude zatím standardně osazovat SHT31. 
Jestli to bude varianta s [kaptonovou páskou](https://www.gme.cz/kaptonova-paska-sirka-3mm), tak to je na @ChroustJan. Tak, aby nemohlo při osazování (resp. mytí) dojít k poškození senzoru.

**Comment by kaklik** [comment]
Možná že by bylo docela dobré, kdyby TFHT01 bylo vyrobeno na tenčím FR4.  Jednak by se tím ušetřila nějaká hmotnost a potom by filtrační čepička lépe pasovala do otvorů. 

![image](https://user-images.githubusercontent.com/1194177/158036758-1104ce66-cbc9-43b6-a747-7d2986e5b27c.png)

Standardní používaná tloušťka PCB 1.6mm totiž vede k této situaci: 

![image](https://user-images.githubusercontent.com/1194177/158037085-d17984dd-dfb9-4b84-a957-8c318278dea5.png)

**Comment by kaklik** [comment]
Jsem to překreslil 

![image](https://user-images.githubusercontent.com/1194177/158038116-f56a8f4a-3339-433f-bd2b-a41028d2ffd0.png)


![image](https://user-images.githubusercontent.com/1194177/158038122-6b40d762-6358-4cc7-a1c0-d87148d813f5.png)

**Comment by ChroustJan** [comment]
PCB bude mít 0,8mm

**Comment by kaklik** [comment]
Lepší by bylo nahradit čepičku vhodně konstruovanou krabičkou. #10
