### ISSUE TITLE
TFHT01 QGCS configuration

### ISSUE THREAD

**Issue by Murali-IsPagro** [ThunderFly-aerospace/TFHT01#6]
I am need to measure temperature at 4 different points. how to configure in QGCS if i am connecting the sensor in pixhawk ? Any link for configuration details or setup details?

**Comment by roman-dvorak** [comment]
Hello, multiple TFHT01 sensors can be connected to an autopilot with PX4 firmware. The firmware produces a multi-instance uORB message and logs it. 

Two sensors can be connected to one bus (with changed address). If you need to connect more sensors, this can be solved by our I2C address translator [TFI2CADT01](https://github.com/ThunderFly-aerospace/TFI2CADT01). We can offer it as a complete solution. 

The message is also sent to MAVLINK network. It can be displayed in the QGC [Mavlink inspector](https://docs.qgroundcontrol.com/master/en/analyze_view/mavlink_inspector.html) tool. 

What type of autopilot you want to use? Sensor support can be enabled by setting the [SENS_EN_SHT3X](http://docs.px4.io/master/en/advanced_config/parameter_reference.html#SENS_EN_SHT3X) parameter to 1.

**Comment by Murali-IsPagro** [comment]
I will be using px4 firmware, Pixhawk 2.4.8. You gave me an answer . "Sensor support can be enabled by setting the [SENS_EN_SHT3X](http://docs.px4.io/master/en/advanced_config/parameter_reference.html#SENS_EN_SHT3X) parameter to 1." This is what i was looking for. 

Thank you
