### ISSUE TITLE
LED type

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFHT01#8]
Ve verzi 01B bych navrhoval předělat LED do pouzdra 0603. Ty jsme nově začali používat u nových modulů. Potisk na PCB bude z obou stran.

**Comment by kaklik** [comment]
Já myslím, že takové rozhodnutí hodně závisí na základním mechanickém uspořádání, které bude použité pro montáž na UAV. 
 Reverzní montáž LED bych úplně univerzálně u TF modulů nerušil. Jen to u některých nedává tolik smysl.  (Původní plán uvažoval zejména s využitím pro čidla)

Reverzní montáž LED má velkou výhodu v tom, že LED je pak efektivně viditelná ze všech stran PCB.

**Comment by ChroustJan** [comment]
To neumím rozhodnout. Reverzní montáž je složitější. To vím.

**Comment by kaklik** [comment]
> To neumím rozhodnout. Reverzní montáž je složitější. To vím.

V čem je reverzní montáž složitější, když se použijí LED pro reverzní montáž určené? 

Já tady ve zrušení té reverzní montáže.  (a obecně u čidel) nevidím velký smysl.  Podle mě je v případě předpokládané montáže senzoru #10  dokonce výhodné, aby LED svítila hlavně na opačnou stranu než je čidlo.  Citlivá část čidla pak může být otočena směrem dolů a tím se v čidle nebude držet voda ani prach. Naopak LED budou z vrchní i spodní strany pravděpodobně snadno viditelné.

**Comment by ChroustJan** [comment]
Je potřeba tedy vyřešit správnost footprint. Kvůli DRC se posunuli plošky. Je tedy potřeba přidávat větší množství pasty a někdy i ruční oprava. Dochází k přitažení LED k jedné straně a na druhé straně není kontakt vůbec.

**Comment by kaklik** [comment]
> Je potřeba tedy vyřešit správnost footprint. Kvůli DRC se posunuli plošky. Je tedy potřeba přidávat větší množství pasty a někdy i ruční oprava. Dochází k přitažení LED k jedné straně a na druhé straně není kontakt vůbec.

Myslím že je chyba řešit chybovou hlášku DRC úpravou footprintu, pokud úprava způsobí technologické potíže.  (Smysl DRC je přesně opačný). 
Navíc chybovou hlášku DRC je možné skrýt, čímž přestane generovat neprůchodný výsledek testu.

**Comment by ChroustJan** [comment]
Navrhuji vyzkoušet pouzdro, které dal @roman-dvorak  do TFRPM01D. Zavádí příplatkové vnitřní frézování, ale mělo by to řešit problém s osazováním. Nevím zda @roman-dvorak  kontrolovat zda se do díry LED opravdu vejde.

**Comment by ChroustJan** [comment]
Romanova změna nebyla dobrá. Udělal jsem jinou. Aktuálně se problém při osazování snížil na minimum.

**Comment by kaklik** [comment]
> Romanova změna nebyla dobrá. Udělal jsem jinou. Aktuálně se problém při osazování snížil na minimum.

A skutečně to zavádí nějaký příplatek za vnitřní frézování, nebo to stojí stejně?
