### ISSUE TITLE
Distance of conductive paths from drilled holes

### ISSUE THREAD

**Issue by ChroustJan** [ThunderFly-aerospace/TFHT01#9]
Je potřeba si ohlídat vzdálenost vodivých cest od vrtaných otvorů. Přijdou mi dost blízko (cca 0,1mm):
![image](https://user-images.githubusercontent.com/9783606/158366094-67e31e1a-ac2c-4408-9761-3e2b29dc9708.png)

Snažil jsem se najít nějakou informaci u výrobce, ale nenašel jsem. Jediné co tam mají je vzdálenost mědi od frézování a ta je definovaná jako 0,15mm. Tak bych považoval za rozumné nastavit aspoň tu. Ideálně klidně i větší.

**Comment by kaklik** [comment]
Ok, opravíš to, nebo nastavíš to prosím rovnou v tom projektu? 

Je tam ještě obdobný problém.. vzdálenosti děr pro CAP-SF2 o okrajů desky. To taktéž nevím zda je nyní správně.

**Comment by ChroustJan** [comment]
Pokud na tom budu pracovat tak to opravím.

CAP-SF2 je takto špatně. Hrozí že tam bude drážkování a tam je dobré dodržet minimálně 0,5mm vzdálenost mědi od okraje a pak ještě rezervu, aby se to nevylamovalo.

**Comment by kaklik** [comment]
> Pokud na tom budu pracovat tak to opravím.
> 
> CAP-SF2 je takto špatně. Hrozí že tam bude drážkování a tam je dobré dodržet minimálně 0,5mm vzdálenost mědi od okraje a pak ještě rezervu, aby se to nevylamovalo.

CAP-SF2 ale žádnou měď nepoužívá.

**Comment by ChroustJan** [comment]
Těch 0,5mm jsem myslel ve smyslu ochranného pásma pro drážkování. Navrhoval bych jako minimum pro vrtanou díru aspoň 2,5mm. Spíš možná i 3,5mm. Je potřeba brát ohled na nožičky CAP-SF2, že za něco musí držet: 
![image](https://user-images.githubusercontent.com/9783606/158390520-5be08b61-7510-4aa7-aba3-db3e7876f345.png)

**Comment by kaklik** [comment]
> Těch 0,5mm jsem myslel ve smyslu ochranného pásma pro drážkování. Navrhoval bych jako minimum pro vrtanou díru aspoň 2,5mm. Spíš možná i 3,5mm. Je potřeba brát ohled na nožičky CAP-SF2, že za něco musí držet: ![image](https://user-images.githubusercontent.com/9783606/158390520-5be08b61-7510-4aa7-aba3-db3e7876f345.png)

Aby tyhle packy měly ten smysl ke kterému jsou zamýšlené, tak by to PCB muselo mít přibližně poloviční tloušťku.

**Comment by roman-dvorak** [comment]
A nešlo by mít pro packy z druhé strany vyvrtané zahloubení? Obdoba zahloubení pro válcovou hlavu šroubu (viz obrázek) Netuším, jak se to definuje ve výrobních datech, ale to by snad mělo jít domluvit s výrobcem. 

![image](https://user-images.githubusercontent.com/5196729/159079032-c86f9c1e-da6b-459f-8582-63bd87bc1572.png)

Ale je fakt, že tenčí PCB bude mít menší tepelnou kapacitu, což je u tohoto senzoru docela žádoucí.

**Comment by kaklik** [comment]
> A nešlo by mít pro packy z druhé strany vyvrtané zahloubení? Obdoba zahloubení pro válcovou hlavu šroubu (viz obrázek) Netuším, jak se to definuje ve výrobních datech, ale to by snad mělo jít domluvit s výrobcem.
> 
> 
> Ale je fakt, že tenčí PCB bude mít menší tepelnou kapacitu, což je u tohoto senzoru docela žádoucí.

Tohle sice domluvit jde. (Dělá se to tak, že se pošle další vrstva z druhý strany, kde to má být s textovým popisem toho, jak to má být hluboko). Nicméně to bude téměř jistě za příplatek.  
Raději bych tady byl pro variantu tenčího PCB, protože to má myslím smysl jak v ušetření hmotnosti, tak i v menší tepelné kapacitě.    Úplně ideální by zde bylo ridig-flex PCB, ale to je asi pro první produkční verzi takového senzoru asi zbytečný.

**Comment by kaklik** [comment]
Tohle mi připadá vyřešené. Respektive další relevantní diskuse je spíš v #5
